### PR TITLE
New features: custom end sound, start/end commands, progress bar color

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
I've extended this app with some features I'm finding useful, so I thought I'd submit them in a PR for your consideration. From the CLI help: 
```
  -p, --play-sound <filepath>   Play a sound file when the timer expires
  --start-command <filepath>    Execute a shell command ansynchronously at the start of the timer. WARNING: The command is passed directly to a shell with the same user permissions this program runs under -- use with caution!
  --end-command <filepath>      Execute a shell command ansynchronously at the end of the timer. WARNING: The command is passed directly to a shell with the same user permissions this program runs under -- use with caution!
  -c, --progress-color <color>  Color of the progress bar, as a valid colors.js text color (default: "red")
```

 * ```--play-sound``` is useful to customize the sounds played for different timers, and especially useful on systems that aren't supported natively by node-notifier
 * ```--start-command``` and ```--end-command``` are handy for automating any tasks at the beginning/end of a Pomodoro, such as logging start/end timestamps to a tracking file. I personally use it with a script I wrote that plays a sound every X seconds, kind of a mindfulness thing: https://gist.github.com/thehunmonkgroup/f7eb52913c4049d5e35007def3bfe026
 * ```--progress-bar``` is pretty obvious...the red isn't my favorite, and colors.js provides others, so this just exposes those options.

### CODE REVIEW

**Comment by icarcal** [comment]
Awesome work man!
How about we make the play sound default and add an option for start the app on quiet or silent mode?

About the start and end command, can you describe an use case?

I'm planning to rewrite the whole code as ES6 with TS, wanna help out?

Thanks!

**Comment by thehunmonkgroup** [comment]
Sure, I might be interested in helping w/ the rewrite -- my Node chops are decent.

Check my original post for some use cases for the start/end scripts -- I think point #2 in the list covers that pretty well...

I think having the play file by default would be good. We'd need to add a few stock sound files available and pick one that plays when no arg is passed. Currently I play a sample of a crowd cheering and clapping...a little much for a default, but it does give me the option to raise my fist at the end of every Pomodoro. :)

**Comment by icarcal** [comment]
Hey @thehunmonkgroup, tested and it looks awesome.
Going to merge this and work on the rewrite.
Thanks again.

**Comment by thehunmonkgroup** [comment]
@icarcal awesome thanks!

**Pull request merged**
